Sprint 01
Iker-elorrieta/RetoADPSP_4 pull request #1
Opened 2021-12-21 08:47 UTC by ENGEL-DROID

Primer Sprint

2021-12-24 12:35 UTC, Iker-elorrieta requested changes
Faltan algunas tablas en el modelo, además de las claves externas que no estaban correctas en el modelo E-R subido.
Los testes no llegan al mínimo
![image](https://user-images.githubusercontent.com/71759245/147352965-5ae32ea4-0cad-4747-a730-88bfa853882c.png)

Además no se ha llegado a crear ningún elemento en la tabla lugarprueblo.

2022-01-13 10:53 UTC, Iker-elorrieta requested changes
No funciona correctamente.
Creo esta BD:
![image](https://user-images.githubusercontent.com/71759245/149316889-cadb43d8-6045-4f4c-95a9-79a846b28295.png)

Ejecuto y no hace nada.
Las pruebas:

![image](https://user-images.githubusercontent.com/71759245/149317011-2eea122d-0040-4dd1-933a-3cb93486daf1.png)
![image](https://user-images.githubusercontent.com/71759245/149317050-57e6167c-8400-4b73-8b09-72a79fb0ce9c.png)

Algo tenéis incorrecto, por favor, revisarlo en diferentes equipos antes de realizar un pull request.

2022-01-13 11:55 UTC, Aitor12345 commented
No estaba la bdd actualizada

2022-01-13 18:17 UTC, Iker-elorrieta requested changes
El programa en sí no hace nada. No introduce ningún dato en la base de datos. Las pruebas si lo hacen, llegan al 80% muy justo con bastantes errores.
Adjunto errores y clases con pocas pruebas:
![image](https://user-images.githubusercontent.com/71759245/149386271-4e42b31a-33fb-4619-a370-727e03ae47d4.png)
![image](https://user-images.githubusercontent.com/71759245/149386459-638904c2-1ae1-4b19-a8df-b9aa094c13dd.png)
Para pasar al siguiente sprint las clases tienen que estar probadas y el main tiene que introducir un dato en cada tabla de la BD.

2022-01-14 08:12 UTC, Iker-elorrieta requested changes
Lo comentado

2022-01-14 08:15 UTC, Iker-elorrieta commented
Aumentar pruebas para la siguiente. Faltan tablas por informar en la ejecución

2022-01-14 08:18 UTC, merged